#!/usr/bin/env python3
"""Generate include/airports_data.h from OurAirports (public domain data).

Keeps: all large_airport entries, plus medium_airport with an IATA code and
scheduled service. Run from the repo root:
    python3 tools/gen_airports.py
"""
import csv
import io
import urllib.request

URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"
OUT = "include/airports_data.h"


def main():
    raw = urllib.request.urlopen(URL, timeout=60).read().decode("utf-8")
    rows = csv.DictReader(io.StringIO(raw))
    SZ = {"large_airport": 2, "medium_airport": 1, "small_airport": 0}
    airports = []
    for r in rows:
        t = r["type"]
        if t not in SZ:
            continue
        code = (r["iata_code"] or "").strip()
        if not code:
            code = (r["local_code"] or r["gps_code"] or "").strip()
        # Skip entries with no usable short code (e.g. "US-0234" survey ids).
        if not code or len(code) > 4 or "-" in code:
            continue
        try:
            lat = float(r["latitude_deg"])
            lon = float(r["longitude_deg"])
        except ValueError:
            continue
        airports.append((lat, lon, code, SZ[t]))

    airports.sort(key=lambda a: (-a[3], a[2]))
    with open(OUT, "w") as f:
        f.write("// Generated by tools/gen_airports.py from OurAirports\n")
        f.write("// (https://ourairports.com/data/ — public domain).\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("// sz: 2 = large, 1 = medium, 0 = small/GA\n")
        f.write("struct AirportRec { float lat; float lon; char code[5]; uint8_t sz; };\n\n")
        f.write(f"inline constexpr int kAirportCount = {len(airports)};\n")
        f.write("inline const AirportRec kAirports[] = {\n")
        for lat, lon, code, sz in airports:
            f.write(f'    {{{lat:.4f}f, {lon:.4f}f, "{code}", {sz}}},\n')
        f.write("};\n")
    counts = [sum(1 for a in airports if a[3] == s) for s in (2, 1, 0)]
    print(f"wrote {OUT}: {len(airports)} airports "
          f"(large {counts[0]}, medium {counts[1]}, small {counts[2]})")


if __name__ == "__main__":
    main()
